apiVersion: v1
kind: Secret
metadata:
 name: mysqlpwd
data:
 password: b3BzbXhhZG1pbjEyMw==
---
apiVersion: v1
kind: Service
metadata:
 name: mysql-second
 labels:
   app: mysql
spec:
 type: ClusterIP
 selector:
   app: mysql-f50-cd
 ports:
   - port: 3306
     protocol: TCP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
 name: mysql-f50-cd
spec:
 selector:
   matchLabels:
     app: mysql-f50-cd
 serviceName: mysql
 replicas: 1
 template:
   metadata:
     labels:
       app: mysql-f50-cd
   spec:
     terminationGracePeriodSeconds: 10
     containers:
     - name: mysql
       image: mysql:8
       ports:
       - containerPort: 3306
         name: mysql
       env:
       - name: MYSQL_ROOT_PASSWORD
         valueFrom:
           secretKeyRef:
             name: mysqlpwd
             key: password
       - name: MYSQL_DATABASE
         value: "dummy"
       volumeMounts:
       - mountPath: /var/lib/mysql
         name: mysql-f50-cd-volume
 volumeClaimTemplates:
 - metadata:
     name: mysql-f50-cd-volume
   spec:
     storageClassName: gp2 
     accessModes: [ "ReadWriteOnce" ]
     resources:
       requests:
         storage: 6Gi
